[Potential halo]
Type = Spheroid
mass = 1585
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 774
outerCutoffRadius = 5344

[Potential bulge]
Type = Sersic
mass = 18.21
scaleRadius = 44
sersicIndex = 4
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 9
rmaxSph = 5344
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.073
rmaxSph = 264
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.073
rmaxSph = 5344
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 18.21344938936887
J0 = 33.19663863620267
slopeIn = 1.9301829070636307
slopeOut = 4.788785313529706
steepness = 1.4581300863052433
coefJrIn = 0.8771474011374948
coefJrOut = 0.25857864877250925
Jcutoff = 32.613131461456476
cutoffStrength = 19.99997500763105
coefJzIn = 1.8196132112949894
coefJzOut = 2.12511559618937


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.2
# ra_coeff = 2.5
