[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 464
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 5.61
scaleRadius = 37
sersicIndex = 3
axisRatioZ = 0.8

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.062
rmaxSph = 222
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.062
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 5.611334125498693
J0 = 15.243727129861778
slopeIn = 1.7882225784785963
slopeOut = 3.509519914217809
steepness = 1.5121604971804055
coefJrIn = 1.4646261181719198
coefJrOut = 0.4737620994002476
Jcutoff = 22.00831904318829
cutoffStrength = 16.07082772439821
coefJzIn = 0.9863442497994347
coefJzOut = 1.4734427188823365


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.1
# ra_coeff = 2.0
