[Potential halo]
Type = Spheroid
mass = 794
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 471
outerCutoffRadius = 4245

[Potential bulge]
Type = Sersic
mass = 15.36
scaleRadius = 64
sersicIndex = 3
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 7
rmaxSph = 4245
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.107
rmaxSph = 384
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.107
rmaxSph = 4245
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 15.363089805645501
J0 = 10363.296044886696
slopeIn = 1.160600376980595
slopeOut = 8.235984105940872
steepness = 0.2635786480808452
coefJrIn = 1.044497839177271
coefJrOut = 0.3393048613943518
Jcutoff = 35.874398486619604
cutoffStrength = 19.999996215887606
coefJzIn = 1.604402502459506
coefJzOut = 1.7793323816852993


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.1
# ra_coeff = 2.0
