[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 328
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 9.18
scaleRadius = 30
sersicIndex = 4
axisRatioZ = 0.9

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.05
rmaxSph = 180
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.05
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 9.181841421799831
J0 = 27.66479230458457
slopeIn = 1.9185115664927606
slopeOut = 4.534846739999644
steepness = 1.394584213362555
coefJrIn = 1.370414538331631
coefJrOut = 0.38727985862471953
Jcutoff = 29.900961657949992
cutoffStrength = 18.647925091561095
coefJzIn = 0.9150888337344475
coefJzOut = 1.4468345846741995


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.0
# ra_coeff = 2.5
