[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 182
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 2.95
scaleRadius = 25
sersicIndex = 3
axisRatioZ = 0.9

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.042
rmaxSph = 150
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.042
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 2.9506169358212806
J0 = 46181.42522994945
slopeIn = 0.746924288359326
slopeOut = 11.4432488338037
steepness = 0.2000003732189471
coefJrIn = 0.5329392343929791
coefJrOut = 0.41185748227988517
Jcutoff = 10.751754498955199
cutoffStrength = 6.121013232520046
coefJzIn = 0.9851784295843413
coefJzOut = 1.2805323482552586


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.5
# ra_coeff = 1.5
