[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 266
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 5.45
scaleRadius = 36
sersicIndex = 3
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.06
rmaxSph = 216
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.06
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 5.451076220089123
J0 = 151.77664328905152
slopeIn = 1.5949916043897587
slopeOut = 8.727968323384545
steepness = 0.7010488595223708
coefJrIn = 1.1382121491093418
coefJrOut = 0.40783924101004343
Jcutoff = 20.462913830074033
cutoffStrength = 7.506163472242023
coefJzIn = 1.3322136304016965
coefJzOut = 1.7696949784372902


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.0
# ra_coeff = 3.0
