[Potential halo]
Type = Spheroid
mass = 6310
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1199
outerCutoffRadius = 8469

[Potential bulge]
Type = Sersic
mass = 33.78
scaleRadius = 75
sersicIndex = 5
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 14
rmaxSph = 8469
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.125
rmaxSph = 450
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.125
rmaxSph = 8469
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 33.80049921144781
J0 = 114.45185834745354
slopeIn = 1.9836919093943601
slopeOut = 5.928905334588056
steepness = 1.2042604349732953
coefJrIn = 1.1251270905397326
coefJrOut = 0.2582228283907691
Jcutoff = 83.76746825128414
cutoffStrength = 19.999976492759266
coefJzIn = 1.3812311748797572
coefJzOut = 1.9129671407033932


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.1
# ra_coeff = 3.0
