[Potential halo]
Type = Spheroid
mass = 6310
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1949
outerCutoffRadius = 8469

[Potential bulge]
Type = Sersic
mass = 17.5
scaleRadius = 60
sersicIndex = 4
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 14
rmaxSph = 8469
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.1
rmaxSph = 360
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.1
rmaxSph = 8469
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 17.503184006381325
J0 = 46.9798085074605
slopeIn = 1.8924685245683786
slopeOut = 4.3820874407725
steepness = 1.2683795204803543
coefJrIn = 1.2764619279494875
coefJrOut = 0.3378640380527155
Jcutoff = 48.36788597095469
cutoffStrength = 19.999963668281218
coefJzIn = 1.305683461374179
coefJzOut = 1.8289109612674384


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.2
# ra_coeff = 2.5
