[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 328
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 7.25
scaleRadius = 25
sersicIndex = 4
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.042
rmaxSph = 150
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.042
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 7.251345028230548
J0 = 11.71548898158154
slopeIn = 1.9615790735048075
slopeOut = 2.7441295167168303
steepness = 1.6774037351617623
coefJrIn = 1.2761998798555647
coefJrOut = 0.3371632141550068
Jcutoff = 17.83372246367642
cutoffStrength = 19.129205892634953
coefJzIn = 0.8619000600722176
coefJzOut = 1.3314183929224965


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.1
# ra_coeff = 1.5
