[Potential halo]
Type = Spheroid
mass = 3162
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 855
outerCutoffRadius = 6727

[Potential bulge]
Type = Sersic
mass = 22.6
scaleRadius = 51
sersicIndex = 3
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 11
rmaxSph = 6727
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.085
rmaxSph = 306
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.085
rmaxSph = 6727
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 22.60439903193685
J0 = 21.81691431925913
slopeIn = 1.6669623372080746
slopeOut = 1.666962806052808
steepness = 2.1950885431553107
coefJrIn = 2.2837534017481333
coefJrOut = 0.48926193272099466
Jcutoff = 46.72440971476293
cutoffStrength = 4.373351139425616
coefJzIn = 0.3581232991259333
coefJzOut = 1.2553690336395027


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.5
# ra_coeff = 1.5
