[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 403
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 8.05
scaleRadius = 36
sersicIndex = 3
axisRatioZ = 0.9

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.06
rmaxSph = 216
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.06
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 8.051662212630294
J0 = 100.75825963399868
slopeIn = 1.710835523712044
slopeOut = 10.33812550503192
steepness = 1.0644898649640921
coefJrIn = 1.2383707254352334
coefJrOut = 0.4792404982521627
Jcutoff = 31.793149809422076
cutoffStrength = 11.891405286542883
coefJzIn = 0.965617994322527
coefJzOut = 1.3888056642598512


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.1
# ra_coeff = 3.0
