[Potential halo]
Type = Spheroid
mass = 6310
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1106
outerCutoffRadius = 8469

[Potential bulge]
Type = Sersic
mass = 27.56
scaleRadius = 57
sersicIndex = 3
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 14
rmaxSph = 8469
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.095
rmaxSph = 342
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.095
rmaxSph = 8469
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 27.56503729164024
J0 = 48.21824264748971
slopeIn = 1.8041484811856483
slopeOut = 4.570797171941469
steepness = 1.5244027546663168
coefJrIn = 1.1287477375636163
coefJrOut = 0.38921928852265963
Jcutoff = 50.76772078013395
cutoffStrength = 19.999997951991524
coefJzIn = 1.5030465940011892
coefJzOut = 1.8935502529211705


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.2
# ra_coeff = 2.5
