[Potential halo]
Type = Spheroid
mass = 794
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 688
outerCutoffRadius = 4245

[Potential bulge]
Type = Sersic
mass = 10.59
scaleRadius = 58
sersicIndex = 3
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 7
rmaxSph = 4245
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.097
rmaxSph = 348
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.097
rmaxSph = 4245
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 10.592309730197794
J0 = 2.5603478402784274
slopeIn = 1.6861765089840521
slopeOut = 2.0000063581614236
steepness = 2.5615101355873007
coefJrIn = 0.14907821518291436
coefJrOut = 0.409899833610718
Jcutoff = 22.842361677180918
cutoffStrength = 2.478751259445864
coefJzIn = 1.7554980342464785
coefJzOut = 1.933108751934718


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.4
# ra_coeff = 3.0
