[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 650
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 8.42
scaleRadius = 29
sersicIndex = 3
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.048
rmaxSph = 174
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.048
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 8.421639037334494
J0 = 136.84210196599037
slopeIn = 1.617701298099434
slopeOut = 11.764138663138128
steepness = 0.9104908429423533
coefJrIn = 0.43033784969074657
coefJrOut = 0.3904641169540943
Jcutoff = 19.488405592441758
cutoffStrength = 19.999998998232257
coefJzIn = 1.2848310751546268
coefJzOut = 1.304767941522953


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.5
# ra_coeff = 1.5
