[Potential halo]
Type = Spheroid
mass = 6310
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1280
outerCutoffRadius = 8469

[Potential bulge]
Type = Sersic
mass = 29.45
scaleRadius = 90
sersicIndex = 4
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 14
rmaxSph = 8469
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.15
rmaxSph = 540
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.15
rmaxSph = 8469
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 29.455525503561567
J0 = 49.33662789967391
slopeIn = 1.946146326410709
slopeOut = 4.007476663077856
steepness = 1.580973466403577
coefJrIn = 1.1011302685479367
coefJrOut = 0.2647880506900809
Jcutoff = 58.238137399066375
cutoffStrength = 19.999996889449168
coefJzIn = 1.6815104245620134
coefJzOut = 2.1474684222827456


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.5
# ra_coeff = 2.5
