[Potential halo]
Type = Spheroid
mass = 6310
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1209
outerCutoffRadius = 8469

[Potential bulge]
Type = Sersic
mass = 31.17
scaleRadius = 58
sersicIndex = 4
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 14
rmaxSph = 8469
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.097
rmaxSph = 348
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.097
rmaxSph = 8469
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 31.175656073244255
J0 = 65.64368990943849
slopeIn = 1.9020072088383986
slopeOut = 4.752026265951049
steepness = 1.3448148092014813
coefJrIn = 1.3778512358261361
coefJrOut = 0.3506584593150666
Jcutoff = 67.15011555925334
cutoffStrength = 19.999960076647596
coefJzIn = 1.2444545805477232
coefJzOut = 1.8475855617654164


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.3
# ra_coeff = 3.0
