[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 458
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 6.63
scaleRadius = 42
sersicIndex = 3
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.07
rmaxSph = 252
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.07
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 6.6313923091691525
J0 = 14378.902691894074
slopeIn = 1.3504692625553465
slopeOut = 19.99999855690567
steepness = 0.3895337497440934
coefJrIn = 0.6057676842607893
coefJrOut = 0.3741450594911
Jcutoff = 19.673434771812797
cutoffStrength = 6.238010643632915
coefJzIn = 1.6283596107372786
coefJzOut = 1.8213331048313446


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.3
# ra_coeff = 2.0
