[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 247
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 3.14
scaleRadius = 16
sersicIndex = 3
axisRatioZ = 0.7

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.027
rmaxSph = 96
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.027
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.1405920829138476
J0 = 5.8438416091864225
slopeIn = 1.815058414492526
slopeOut = 2.8720936248594104
steepness = 1.642857014655704
coefJrIn = 1.7240140118292735
coefJrOut = 0.47886960018601105
Jcutoff = 10.218251483906228
cutoffStrength = 19.999512877063488
coefJzIn = 0.9453082370624588
coefJzOut = 1.606057052272662


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.4
# ra_coeff = 2.0
