[Potential halo]
Type = Spheroid
mass = 6310
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1833
outerCutoffRadius = 8469

[Potential bulge]
Type = Sersic
mass = 19.38
scaleRadius = 52
sersicIndex = 4
axisRatioZ = 0.3

[SelfConsistentModel halo]
rminSph = 14
rmaxSph = 8469
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.087
rmaxSph = 312
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.087
rmaxSph = 8469
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 19.383613940408097
J0 = 257.4097705264863
slopeIn = 1.7984248067673865
slopeOut = 7.887352438195199
steepness = 0.7096475930082299
coefJrIn = 0.3277137455609588
coefJrOut = 0.19009538111175903
Jcutoff = 26.734989608523243
cutoffStrength = 11.4465712480311
coefJzIn = 2.2543529976803534
coefJzOut = 2.12619321694019


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.3
# ra_coeff = 1.5
