[Potential halo]
Type = Spheroid
mass = 3162
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1513
outerCutoffRadius = 6727

[Potential bulge]
Type = Sersic
mass = 15.32
scaleRadius = 67
sersicIndex = 3
axisRatioZ = 0.3

[SelfConsistentModel halo]
rminSph = 11
rmaxSph = 6727
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.112
rmaxSph = 402
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.112
rmaxSph = 6727
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 15.32295695197924
J0 = 37.548717066531445
slopeIn = 1.7420307276580846
slopeOut = 3.062006429496043
steepness = 0.8055383885982004
coefJrIn = 0.4585937739771802
coefJrOut = 0.2580545675049751
Jcutoff = 26.54608512428273
cutoffStrength = 19.999999505355085
coefJzIn = 2.330410810075776
coefJzOut = 2.076256407850153


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.0
# ra_coeff = 1.5
