[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 391
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 4.89
scaleRadius = 24
sersicIndex = 3
axisRatioZ = 0.7

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.04
rmaxSph = 144
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.04
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 4.890944748926401
J0 = 1.8654784039231609
slopeIn = 1.6825480939714785
slopeOut = 2.140281177186592
steepness = 2.27162949917764
coefJrIn = 0.41777421384772373
coefJrOut = 0.5734591723322314
Jcutoff = 14.096279022351329
cutoffStrength = 2.4544577208584566
coefJzIn = 1.0809991216268362
coefJzOut = 1.4619604954559384


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.4
# ra_coeff = 3.0
