[Potential halo]
Type = Spheroid
mass = 3162
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 899
outerCutoffRadius = 6727

[Potential bulge]
Type = Sersic
mass = 19.75
scaleRadius = 60
sersicIndex = 4
axisRatioZ = 0.9

[SelfConsistentModel halo]
rminSph = 11
rmaxSph = 6727
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.1
rmaxSph = 360
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.1
rmaxSph = 6727
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 19.753872692252738
J0 = 44.89634883963229
slopeIn = 1.9537154195188864
slopeOut = 3.6749239442948007
steepness = 1.6242060316017082
coefJrIn = 1.631862200609184
coefJrOut = 0.41747454650895116
Jcutoff = 62.46522870838535
cutoffStrength = 13.053066003651422
coefJzIn = 0.7929760657915109
coefJzOut = 1.4350262020256195


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.2
# ra_coeff = 2.5
