[Potential halo]
Type = Spheroid
mass = 3162
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1224
outerCutoffRadius = 6727

[Potential bulge]
Type = Sersic
mass = 15.41
scaleRadius = 50
sersicIndex = 5
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 11
rmaxSph = 6727
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.083
rmaxSph = 300
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.083
rmaxSph = 6727
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 15.414375614409897
J0 = 357.5945221830545
slopeIn = 1.829679589475899
slopeOut = 15.562311427946078
steepness = 0.799195021850077
coefJrIn = 0.4001069270882378
coefJrOut = 0.263373262166389
Jcutoff = 40.63279565122224
cutoffStrength = 17.789347854380694
coefJzIn = 1.5863684623502576
coefJzOut = 1.9219719883517947


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.5
# ra_coeff = 2.5
