[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 328
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 3.15
scaleRadius = 24
sersicIndex = 3
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.04
rmaxSph = 144
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.04
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.1506087426777305
J0 = 12.020149518561144
slopeIn = 1.795729770293565
slopeOut = 3.7746558927957152
steepness = 1.2211873138138636
coefJrIn = 1.3344053195422
coefJrOut = 0.4025824589688645
Jcutoff = 11.673801346313537
cutoffStrength = 19.999999758373214
coefJzIn = 1.2783531683117488
coefJzOut = 1.7290980308660517


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.2
# ra_coeff = 2.5
