[Potential halo]
Type = Spheroid
mass = 3162
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 818
outerCutoffRadius = 6727

[Potential bulge]
Type = Sersic
mass = 24.71
scaleRadius = 51
sersicIndex = 4
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 11
rmaxSph = 6727
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.085
rmaxSph = 306
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.085
rmaxSph = 6727
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 24.714567648416985
J0 = 57.48586674908854
slopeIn = 1.9588735890787647
slopeOut = 4.0935701607973884
steepness = 1.6339587566551281
coefJrIn = 1.8407270500052908
coefJrOut = 0.4414937775872168
Jcutoff = 73.50134317054844
cutoffStrength = 19.99999899249719
coefJzIn = 0.5796364749973546
coefJzOut = 1.2792531112063916


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.3
# ra_coeff = 3.0
