[Potential halo]
Type = Spheroid
mass = 1585
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1188
outerCutoffRadius = 5344

[Potential bulge]
Type = Sersic
mass = 14.93
scaleRadius = 44
sersicIndex = 4
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 9
rmaxSph = 5344
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.073
rmaxSph = 264
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.073
rmaxSph = 5344
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 14.932751248067818
J0 = 131.11808284618817
slopeIn = 1.7913266345987133
slopeOut = 7.861994929745061
steepness = 0.8808372423698493
coefJrIn = 1.1005030821372717
coefJrOut = 0.3010450738477227
Jcutoff = 39.9195961559104
cutoffStrength = 19.999997780419296
coefJzIn = 1.3660250733469517
coefJzOut = 1.857262386765259


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.0
# ra_coeff = 3.0
