[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 353
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 5.47
scaleRadius = 30
sersicIndex = 4
axisRatioZ = 0.8

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.05
rmaxSph = 180
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.05
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 5.471104773321149
J0 = 833.2432262312699
slopeIn = 1.6387160696946754
slopeOut = 12.67809330313499
steepness = 0.5288795553817586
coefJrIn = 0.9054425957357125
coefJrOut = 0.32508714579438913
Jcutoff = 20.476171839728966
cutoffStrength = 12.270291232556017
coefJzIn = 1.1310987780540687
coefJzOut = 1.5860284849109503


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.3
# ra_coeff = 2.5
