[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 456
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 4.25
scaleRadius = 24
sersicIndex = 3
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.04
rmaxSph = 144
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.04
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 4.250821319484064
J0 = 29.696385417512687
slopeIn = 1.7182598652477352
slopeOut = 6.405025585122053
steepness = 1.0527087903904133
coefJrIn = 1.2259545394660039
coefJrOut = 0.41074093630560726
Jcutoff = 14.989469956423735
cutoffStrength = 12.107853537607538
coefJzIn = 1.3038826177465623
coefJzOut = 1.77000625361191


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.1
# ra_coeff = 3.0
