[Potential halo]
Type = Spheroid
mass = 1585
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 838
outerCutoffRadius = 5344

[Potential bulge]
Type = Sersic
mass = 11.83
scaleRadius = 46
sersicIndex = 4
axisRatioZ = 0.8

[SelfConsistentModel halo]
rminSph = 9
rmaxSph = 5344
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.077
rmaxSph = 276
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.077
rmaxSph = 5344
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 11.832502717835181
J0 = 14361.647334088093
slopeIn = 1.5141741878988586
slopeOut = 19.999993855962273
steepness = 0.41767434800926606
coefJrIn = 0.9596174152767469
coefJrOut = 0.3124527824567421
Jcutoff = 37.63977907808671
cutoffStrength = 9.424276595087953
coefJzIn = 1.113546748045808
coefJzOut = 1.5694457039147516


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.3
# ra_coeff = 2.5
