[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 401
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 6.2
scaleRadius = 34
sersicIndex = 3
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.057
rmaxSph = 204
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.057
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 6.201208250053698
J0 = 41.739811651709175
slopeIn = 1.6930463752492795
slopeOut = 4.890294778339303
steepness = 0.9487282000500619
coefJrIn = 0.6124876903738686
coefJrOut = 0.3879272851960669
Jcutoff = 18.704855662682554
cutoffStrength = 10.653499070363477
coefJzIn = 1.1937561548130657
coefJzOut = 1.3060363574019664


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.4
# ra_coeff = 1.5
