[Potential halo]
Type = Spheroid
mass = 6310
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 2075
outerCutoffRadius = 8469

[Potential bulge]
Type = Sersic
mass = 24.4
scaleRadius = 71
sersicIndex = 4
axisRatioZ = 0.8

[SelfConsistentModel halo]
rminSph = 14
rmaxSph = 8469
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.118
rmaxSph = 426
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.118
rmaxSph = 8469
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 24.4053487611581
J0 = 34.51487096416623
slopeIn = 1.9859515554801266
slopeOut = 2.525108595322265
steepness = 1.8361554774626199
coefJrIn = 1.4547459786153938
coefJrOut = 0.35630193718865233
Jcutoff = 55.56927614153089
cutoffStrength = 17.956859522624462
coefJzIn = 1.033806255220002
coefJzOut = 1.5005262151207341


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.2
# ra_coeff = 1.5
