[Potential halo]
Type = Spheroid
mass = 794
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 508
outerCutoffRadius = 4245

[Potential bulge]
Type = Sersic
mass = 9.21
scaleRadius = 46
sersicIndex = 3
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 7
rmaxSph = 4245
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.077
rmaxSph = 276
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.077
rmaxSph = 4245
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 9.211923667932563
J0 = 15.322030672077217
slopeIn = 1.8201988425773288
slopeOut = 2.996341471709772
steepness = 1.6457269297601027
coefJrIn = 1.3536345000583012
coefJrOut = 0.39738483226771243
Jcutoff = 24.529918303183354
cutoffStrength = 17.283659086005084
coefJzIn = 1.3898020003531193
coefJzOut = 1.8787717362591698


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.4
# ra_coeff = 2.0
