[Potential halo]
Type = Spheroid
mass = 794
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 617
outerCutoffRadius = 4245

[Potential bulge]
Type = Sersic
mass = 9.46
scaleRadius = 37
sersicIndex = 4
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 7
rmaxSph = 4245
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.062
rmaxSph = 222
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.062
rmaxSph = 4245
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 9.46187809270657
J0 = 32.99138748002721
slopeIn = 1.8816666236579978
slopeOut = 4.634061389078469
steepness = 1.1272820483648043
coefJrIn = 0.9078943796581491
coefJrOut = 0.31234743137179566
Jcutoff = 25.4738728362536
cutoffStrength = 19.999996984464804
coefJzIn = 1.4801342563150224
coefJzOut = 1.7666864130874795


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.1
# ra_coeff = 2.0
