[Potential halo]
Type = Spheroid
mass = 794
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 541
outerCutoffRadius = 4245

[Potential bulge]
Type = Sersic
mass = 11.28
scaleRadius = 39
sersicIndex = 4
axisRatioZ = 0.8

[SelfConsistentModel halo]
rminSph = 7
rmaxSph = 4245
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.065
rmaxSph = 234
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.065
rmaxSph = 4245
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 11.282248341044431
J0 = 20.083335212794225
slopeIn = 1.9636394021461612
slopeOut = 2.892306704945849
steepness = 1.7717559915576855
coefJrIn = 1.7335928246238121
coefJrOut = 0.39789550289471354
Jcutoff = 32.836189022962756
cutoffStrength = 19.78388858372822
coefJzIn = 0.852918187808829
coefJzOut = 1.5470236169228049


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.4
# ra_coeff = 2.0
