[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 497
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 6.0
scaleRadius = 26
sersicIndex = 3
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.043
rmaxSph = 156
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.043
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 6.001119292141654
J0 = 87.34123535131712
slopeIn = 1.621924216325066
slopeOut = 5.8669542037615985
steepness = 0.6202862329334003
coefJrIn = 0.7638819445490452
coefJrOut = 0.2927976406448453
Jcutoff = 12.791245230892612
cutoffStrength = 19.999990206274102
coefJzIn = 1.8897635785234845
coefJzOut = 1.9960991402167043


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.0
# ra_coeff = 2.0
