[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 466
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 5.91
scaleRadius = 38
sersicIndex = 4
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.063
rmaxSph = 228
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.063
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 5.9111004993097795
J0 = 28.541594311510295
slopeIn = 1.8784969863035688
slopeOut = 5.758577110957354
steepness = 1.2102922332424177
coefJrIn = 1.1162809809302585
coefJrOut = 0.2976990589821429
Jcutoff = 21.259660262593332
cutoffStrength = 19.99999962144668
coefJzIn = 1.5122080736320636
coefJzOut = 1.9997095322849734


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.2
# ra_coeff = 3.0
