[Potential halo]
Type = Spheroid
mass = 794
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 638
outerCutoffRadius = 4245

[Potential bulge]
Type = Sersic
mass = 8.38
scaleRadius = 55
sersicIndex = 4
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 7
rmaxSph = 4245
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.092
rmaxSph = 330
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.092
rmaxSph = 4245
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 8.381553320206855
J0 = 26.966463532641978
slopeIn = 1.9809143603149617
slopeOut = 3.2635955001982393
steepness = 1.7453070718326713
coefJrIn = 1.8480341851062652
coefJrOut = 0.4308018831033711
Jcutoff = 40.03790082198089
cutoffStrength = 19.999999019197958
coefJzIn = 0.5759829074468674
coefJzOut = 1.2845990584483145


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.3
# ra_coeff = 2.5
