[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 192
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 3.88
scaleRadius = 26
sersicIndex = 4
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.043
rmaxSph = 156
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.043
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.8808275721619303
J0 = 8.108454913750812
slopeIn = 1.9407723473394238
slopeOut = 2.8182909495970407
steepness = 1.5860338522288957
coefJrIn = 1.1944928978904514
coefJrOut = 0.3146764156158514
Jcutoff = 12.200371945587898
cutoffStrength = 19.999997218215608
coefJzIn = 1.4137043302190235
coefJzOut = 1.735959565970556


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.2
# ra_coeff = 1.5
