[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 305
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 4.83
scaleRadius = 25
sersicIndex = 4
axisRatioZ = 0.3

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.042
rmaxSph = 150
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.042
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 4.830900209093654
J0 = 233.86117805394605
slopeIn = 1.6493947265546982
slopeOut = 10.271576935171954
steepness = 0.5454267494075866
coefJrIn = 0.6997082630114623
coefJrOut = 0.16881385764293919
Jcutoff = 10.282629666325173
cutoffStrength = 13.324122399645889
coefJzIn = 2.0798842562763324
coefJzOut = 2.323071630912314


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.1
# ra_coeff = 3.0
