[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 462
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 6.67
scaleRadius = 41
sersicIndex = 4
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.068
rmaxSph = 246
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.068
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 6.671243194570604
J0 = 21.551225369908494
slopeIn = 1.9214528413053686
slopeOut = 4.063814225755324
steepness = 1.309405149022857
coefJrIn = 0.9465316378464868
coefJrOut = 0.2799926254870779
Jcutoff = 20.177955400716638
cutoffStrength = 19.99999179602366
coefJzIn = 1.6466078227614889
coefJzOut = 1.9238061507548287


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.1
# ra_coeff = 2.0
