[Potential halo]
Type = Spheroid
mass = 1585
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 659
outerCutoffRadius = 5344

[Potential bulge]
Type = Sersic
mass = 17.29
scaleRadius = 42
sersicIndex = 4
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 9
rmaxSph = 5344
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.07
rmaxSph = 252
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.07
rmaxSph = 5344
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 17.293269338646613
J0 = 18.940620903332828
slopeIn = 1.9751627231502218
slopeOut = 2.717882132922694
steepness = 1.7882568533800254
coefJrIn = 0.7718591765647224
coefJrOut = 0.24893028797703337
Jcutoff = 26.05680907634402
cutoffStrength = 19.999974389257662
coefJzIn = 1.9495134703192565
coefJzOut = 2.0013463919047605


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.2
# ra_coeff = 1.5
