[Potential halo]
Type = Spheroid
mass = 1585
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 810
outerCutoffRadius = 5344

[Potential bulge]
Type = Sersic
mass = 18.84
scaleRadius = 49
sersicIndex = 4
axisRatioZ = 0.7

[SelfConsistentModel halo]
rminSph = 9
rmaxSph = 5344
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.082
rmaxSph = 294
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.082
rmaxSph = 5344
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 18.843986025586585
J0 = 22.39218661096694
slopeIn = 1.9761488300855303
slopeOut = 2.249535120286283
steepness = 1.8066319344202117
coefJrIn = 1.6413837064315904
coefJrOut = 0.3564934759953889
Jcutoff = 39.19115942217929
cutoffStrength = 19.999989746296436
coefJzIn = 1.0373907752096698
coefJzOut = 1.6342062781013558


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.5
# ra_coeff = 1.5
