[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 405
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 6.13
scaleRadius = 47
sersicIndex = 3
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.078
rmaxSph = 282
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.078
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 6.131264676713384
J0 = 10.104493256975267
slopeIn = 1.8436745811040671
slopeOut = 2.242500197047896
steepness = 1.8468210682990231
coefJrIn = 1.5395686291120483
coefJrOut = 0.42125689206868994
Jcutoff = 20.207875636907772
cutoffStrength = 13.474345396623097
coefJzIn = 1.186414798959531
coefJzOut = 1.7009393034437068


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.4
# ra_coeff = 1.5
