[Potential halo]
Type = Spheroid
mass = 794
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 465
outerCutoffRadius = 4245

[Potential bulge]
Type = Sersic
mass = 15.54
scaleRadius = 39
sersicIndex = 3
axisRatioZ = 0.8

[SelfConsistentModel halo]
rminSph = 7
rmaxSph = 4245
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.065
rmaxSph = 234
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.065
rmaxSph = 4245
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 15.543654495027841
J0 = 24.77828246471027
slopeIn = 1.816245436726243
slopeOut = 3.2035285635664157
steepness = 1.681024822417211
coefJrIn = 1.9451515376763338
coefJrOut = 0.536373414508141
Jcutoff = 41.667072145811154
cutoffStrength = 19.999987209355155
coefJzIn = 0.716875109212719
coefJzOut = 1.4807541882197541


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.5
# ra_coeff = 2.5
