[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 591
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 10.52
scaleRadius = 47
sersicIndex = 3
axisRatioZ = 0.9

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.078
rmaxSph = 282
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.078
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 10.522176508941206
J0 = 16.673352479244638
slopeIn = 1.757911245234066
slopeOut = 1.7579113097972892
steepness = 1.1147296430714044
coefJrIn = 1.189195925301597
coefJrOut = 0.34202754361739174
Jcutoff = 23.429739542537344
cutoffStrength = 8.181363151845686
coefJzIn = 1.1366160986266645
coefJzOut = 1.3217549865679583


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.0
# ra_coeff = 1.0
