[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 630
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 10.56
scaleRadius = 46
sersicIndex = 3
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.077
rmaxSph = 276
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.077
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 10.56205713162471
J0 = 25.40994420819333
slopeIn = 1.7967372595043234
slopeOut = 3.438183906852349
steepness = 1.4408062244303044
coefJrIn = 1.5275431383399891
coefJrOut = 0.47844805734143825
Jcutoff = 35.192616630429484
cutoffStrength = 19.999995577387438
coefJzIn = 0.7362284308300054
coefJzOut = 1.2607759713292808


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.0
# ra_coeff = 2.0
