[Potential halo]
Type = Spheroid
mass = 1585
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 729
outerCutoffRadius = 5344

[Potential bulge]
Type = Sersic
mass = 18.44
scaleRadius = 77
sersicIndex = 5
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 9
rmaxSph = 5344
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.128
rmaxSph = 462
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.128
rmaxSph = 5344
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 18.4451561659009
J0 = 47.51441287534843
slopeIn = 2.011092842169773
slopeOut = 5.177573999799754
steepness = 1.450750238134054
coefJrIn = 0.9263932224891016
coefJrOut = 0.21107022672257075
Jcutoff = 46.71943990989241
cutoffStrength = 12.605265076400476
coefJzIn = 1.7946528122334267
coefJzOut = 2.2029351033720115


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.3
# ra_coeff = 3.0
