[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 413
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 6.1
scaleRadius = 47
sersicIndex = 3
axisRatioZ = 0.9

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.078
rmaxSph = 282
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.078
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 6.101262044154625
J0 = 19.61910481909404
slopeIn = 1.6808720716238665
slopeOut = 1.6808730920055122
steepness = 1.2438613869604493
coefJrIn = 1.4052833259983077
coefJrOut = 0.3300895301248371
Jcutoff = 18.953066799562556
cutoffStrength = 7.4336200886376895
coefJzIn = 1.181110786270653
coefJzOut = 1.2838669034495949


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.4
# ra_coeff = 1.0
