[Potential halo]
Type = Spheroid
mass = 794
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 489
outerCutoffRadius = 4245

[Potential bulge]
Type = Sersic
mass = 7.41
scaleRadius = 39
sersicIndex = 3
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 7
rmaxSph = 4245
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.065
rmaxSph = 234
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.065
rmaxSph = 4245
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 7.4114407713725
J0 = 35.64121623858629
slopeIn = 1.793337807901266
slopeOut = 5.349054429702622
steepness = 1.3940665380534434
coefJrIn = 1.664041533142174
coefJrOut = 0.530014291013926
Jcutoff = 33.4735960808956
cutoffStrength = 19.999998210993773
coefJzIn = 0.667979233428913
coefJzOut = 1.2349928544930369


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.1
# ra_coeff = 3.0
