[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 203
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 4.13
scaleRadius = 24
sersicIndex = 3
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.04
rmaxSph = 144
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.04
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 4.130798129280271
J0 = 13.088794595492331
slopeIn = 1.760717742801546
slopeOut = 4.14949862898645
steepness = 1.2763953833736124
coefJrIn = 1.3448735733472408
coefJrOut = 0.4313144480260676
Jcutoff = 14.133507557914132
cutoffStrength = 15.114114430217573
coefJzIn = 1.2572582246275805
coefJzOut = 1.7514681312170695


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.2
# ra_coeff = 2.5
