[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 433
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 9.08
scaleRadius = 33
sersicIndex = 4
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.055
rmaxSph = 198
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.055
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 9.081823866602964
J0 = 895.5727672870138
slopeIn = 1.708094680479672
slopeOut = 19.999998223255307
steepness = 0.6641594783161641
coefJrIn = 0.8648347283393263
coefJrOut = 0.30055888281676385
Jcutoff = 26.5332133054132
cutoffStrength = 12.662613948119255
coefJzIn = 1.416992346444962
coefJzOut = 1.8559560637143802


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.2
# ra_coeff = 3.0
