[Potential halo]
Type = Spheroid
mass = 794
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 581
outerCutoffRadius = 4245

[Potential bulge]
Type = Sersic
mass = 9.67
scaleRadius = 52
sersicIndex = 4
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 7
rmaxSph = 4245
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.087
rmaxSph = 312
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.087
rmaxSph = 4245
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 9.671789030614296
J0 = 20.94236842571939
slopeIn = 2.020161426515651
slopeOut = 2.2375567094192585
steepness = 2.169189322909208
coefJrIn = 2.026548938141956
coefJrOut = 0.43060750149367766
Jcutoff = 37.123405241943544
cutoffStrength = 19.999993546028342
coefJzIn = 0.48672553092902193
coefJzOut = 1.284696249253161


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.5
# ra_coeff = 2.0
