[Potential halo]
Type = Spheroid
mass = 794
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 687
outerCutoffRadius = 4245

[Potential bulge]
Type = Sersic
mass = 11.67
scaleRadius = 59
sersicIndex = 5
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 7
rmaxSph = 4245
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.098
rmaxSph = 354
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.098
rmaxSph = 4245
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 11.673156472732718
J0 = 34.66149211580172
slopeIn = 1.8188047689925524
slopeOut = 5.406860123880206
steepness = 0.9016266308940518
coefJrIn = 0.29849321969867026
coefJrOut = 0.25389337637734655
Jcutoff = 34.84309838307495
cutoffStrength = 13.08137422277357
coefJzIn = 1.8370476092600518
coefJzOut = 2.0359971654258278


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.5
# ra_coeff = 2.0
