[Potential halo]
Type = Spheroid
mass = 3162
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1153
outerCutoffRadius = 6727

[Potential bulge]
Type = Sersic
mass = 19.58
scaleRadius = 77
sersicIndex = 5
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 11
rmaxSph = 6727
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.128
rmaxSph = 462
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.128
rmaxSph = 6727
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 19.585474931034625
J0 = 69.70082761029957
slopeIn = 1.8318195884883397
slopeOut = 6.138090240697603
steepness = 0.9043385742217968
coefJrIn = 0.2916524834408734
coefJrOut = 0.2568626691991698
Jcutoff = 51.15744112497133
cutoffStrength = 16.068169830117526
coefJzIn = 1.880891266608369
coefJzOut = 2.0062585213516626


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.5
# ra_coeff = 2.0
