[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 631
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 7.08
scaleRadius = 36
sersicIndex = 4
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.06
rmaxSph = 216
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.06
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 7.081237508652013
J0 = 9.950227242923095
slopeIn = 1.983022376672903
slopeOut = 2.3621908105639995
steepness = 1.7774951735950637
coefJrIn = 0.9155635879759997
coefJrOut = 0.25586233034595096
Jcutoff = 15.289480567212445
cutoffStrength = 19.99995100542461
coefJzIn = 1.8743056118466856
coefJzOut = 2.029212337076876


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.4
# ra_coeff = 1.5
