[Potential halo]
Type = Spheroid
mass = 3162
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1174
outerCutoffRadius = 6727

[Potential bulge]
Type = Sersic
mass = 22.85
scaleRadius = 57
sersicIndex = 4
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 11
rmaxSph = 6727
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.095
rmaxSph = 342
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.095
rmaxSph = 6727
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 22.85429317280841
J0 = 26.927765005628252
slopeIn = 1.9536294321465482
slopeOut = 3.127139266483507
steepness = 1.656014564830972
coefJrIn = 1.085858817697702
coefJrOut = 0.26182442394129757
Jcutoff = 37.288912411564255
cutoffStrength = 19.034015730388507
coefJzIn = 1.711297188969391
coefJzOut = 2.1124882646319105


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.5
# ra_coeff = 2.0
