[Potential halo]
Type = Spheroid
mass = 3162
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1006
outerCutoffRadius = 6727

[Potential bulge]
Type = Sersic
mass = 25.51
scaleRadius = 95
sersicIndex = 4
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 11
rmaxSph = 6727
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.158
rmaxSph = 570
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.158
rmaxSph = 6727
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 25.514817611293946
J0 = 38.70266317084903
slopeIn = 1.9601111652473626
slopeOut = 2.8268445014344676
steepness = 1.5486304970716307
coefJrIn = 0.6871059895598322
coefJrOut = 0.2446590975623465
Jcutoff = 48.42192191267796
cutoffStrength = 15.87532443149381
coefJzIn = 2.0136352320643254
coefJzOut = 1.9796490293694242


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.1
# ra_coeff = 1.5
