[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 205
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 4.12
scaleRadius = 22
sersicIndex = 3
axisRatioZ = 0.9

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.037
rmaxSph = 132
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.037
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 4.120884212511265
J0 = 14.014802656021327
slopeIn = 1.8197833856103622
slopeOut = 4.349529392023849
steepness = 1.6218259075631372
coefJrIn = 1.8037964865689784
coefJrOut = 0.5553637608372726
Jcutoff = 18.407400505186104
cutoffStrength = 17.19275512296472
coefJzIn = 0.7012340783622957
coefJzOut = 1.3522164163971073


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.3
# ra_coeff = 3.0
