[Potential halo]
Type = Spheroid
mass = 6310
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1893
outerCutoffRadius = 8469

[Potential bulge]
Type = Sersic
mass = 29.04
scaleRadius = 63
sersicIndex = 3
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 14
rmaxSph = 8469
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.105
rmaxSph = 378
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.105
rmaxSph = 8469
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 29.045594572740907
J0 = 145.52719089244258
slopeIn = 1.687729729293071
slopeOut = 6.700977800343925
steepness = 0.9785263910915711
coefJrIn = 1.2398393639236875
coefJrOut = 0.4075316792564514
Jcutoff = 63.351467488879834
cutoffStrength = 13.603439368866873
coefJzIn = 1.297958395184008
coefJzOut = 1.7668003270836812


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.1
# ra_coeff = 3.0
