[Potential halo]
Type = Spheroid
mass = 6310
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1845
outerCutoffRadius = 8469

[Potential bulge]
Type = Sersic
mass = 18.48
scaleRadius = 43
sersicIndex = 3
axisRatioZ = 0.7

[SelfConsistentModel halo]
rminSph = 14
rmaxSph = 8469
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.072
rmaxSph = 258
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.072
rmaxSph = 8469
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 18.48373751089216
J0 = 299.1246108232251
slopeIn = 1.6983130505968684
slopeOut = 8.888444879911338
steepness = 0.8622409273781235
coefJrIn = 0.4625194573352858
coefJrOut = 0.3489445348967132
Jcutoff = 30.20171699700454
cutoffStrength = 19.999987943203866
coefJzIn = 1.413945139233565
coefJzOut = 1.3099289469464452


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.4
# ra_coeff = 1.0
