[Potential halo]
Type = Spheroid
mass = 6310
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 2071
outerCutoffRadius = 8469

[Potential bulge]
Type = Sersic
mass = 21.92
scaleRadius = 70
sersicIndex = 4
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 14
rmaxSph = 8469
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.117
rmaxSph = 420
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.117
rmaxSph = 8469
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 21.92409784703172
J0 = 51.12670117760164
slopeIn = 1.9425966570164148
slopeOut = 1.942597775224541
steepness = 1.0585390300545243
coefJrIn = 2.0796478235277376
coefJrOut = 0.3281826156437483
Jcutoff = 62.574999723582785
cutoffStrength = 4.4427254113188095
coefJzIn = 0.4601760882361312
coefJzOut = 1.3359086921781258


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.5
# ra_coeff = 2.0
