[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 560
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 5.81
scaleRadius = 31
sersicIndex = 3
axisRatioZ = 0.3

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.052
rmaxSph = 186
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.052
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 5.811099047673426
J0 = 0.7527261847843895
slopeIn = 1.4422205317006347
slopeOut = 1.8644699921529773
steepness = 1.8478774116039705
coefJrIn = 0.008704549655743313
coefJrOut = 0.28799826325648026
Jcutoff = 9.745124686263136
cutoffStrength = 3.3612265251792635
coefJzIn = 2.3566397996106954
coefJzOut = 2.0680903734680864


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.5
# ra_coeff = 1.5
