[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 232
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 3.26
scaleRadius = 33
sersicIndex = 3
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.055
rmaxSph = 198
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.055
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.260698813444209
J0 = 223110.39993450118
slopeIn = 0.8815656057183916
slopeOut = 13.59498498253095
steepness = 0.20000000074560478
coefJrIn = 0.6864652708534426
coefJrOut = 0.3531848161882803
Jcutoff = 11.400409901827144
cutoffStrength = 7.778332947481201
coefJzIn = 1.7510916220695825
coefJzOut = 1.7185046972472444


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.3
# ra_coeff = 1.5
