[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 319
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 3.75
scaleRadius = 35
sersicIndex = 4
axisRatioZ = 0.9

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.058
rmaxSph = 210
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.058
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.75074572690166
J0 = 14.465186267501032
slopeIn = 1.961966896839925
slopeOut = 3.533341751933743
steepness = 1.6798235908234473
coefJrIn = 1.7397202126535811
coefJrOut = 0.42239292502365355
Jcutoff = 20.754406309531888
cutoffStrength = 19.286801240381283
coefJzIn = 0.740303556341476
coefJzOut = 1.4368089002498117


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.3
# ra_coeff = 2.5
