[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 290
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 4.44
scaleRadius = 24
sersicIndex = 3
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.04
rmaxSph = 144
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.04
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 4.4408306731636955
J0 = 5.682193582568209
slopeIn = 1.8272194102577297
slopeOut = 2.3484041582465522
steepness = 1.4055343472090127
coefJrIn = 0.9871531653944825
coefJrOut = 0.3144930425563314
Jcutoff = 9.708767149280662
cutoffStrength = 19.999997317611403
coefJzIn = 1.8132564922978873
coefJzOut = 1.9899572035911464


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.3
# ra_coeff = 1.5
