[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 473
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 4.34
scaleRadius = 29
sersicIndex = 4
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.048
rmaxSph = 174
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.048
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 4.3435179775618735
J0 = 16.331789283474247
slopeIn = 1.8947202172237545
slopeOut = 4.497225154668907
steepness = 1.3213545673229938
coefJrIn = 1.4882638797761285
coefJrOut = 0.35232647639646064
Jcutoff = 17.981927379485445
cutoffStrength = 18.000493716020895
coefJzIn = 1.1786163610528455
coefJzOut = 1.85918444180773


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.4
# ra_coeff = 3.0
