[Potential halo]
Type = Spheroid
mass = 3162
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 855
outerCutoffRadius = 6727

[Potential bulge]
Type = Sersic
mass = 20.04
scaleRadius = 70
sersicIndex = 5
axisRatioZ = 0.7

[SelfConsistentModel halo]
rminSph = 11
rmaxSph = 6727
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.117
rmaxSph = 420
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.117
rmaxSph = 6727
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 20.046152286524674
J0 = 765.5270751957796
slopeIn = 1.8278574160136813
slopeOut = 13.622851914259934
steepness = 0.7158908773634691
coefJrIn = 0.6743636383531333
coefJrOut = 0.2763460403383885
Jcutoff = 65.89999557767824
cutoffStrength = 9.69461093489869
coefJzIn = 1.2797903162550248
coefJzOut = 1.7570650998722874


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.4
# ra_coeff = 3.0
