[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 317
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 6.68
scaleRadius = 39
sersicIndex = 4
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.065
rmaxSph = 234
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.065
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 6.681243621059871
J0 = 40.87036038591102
slopeIn = 1.8587111416271969
slopeOut = 3.8101815517328954
steepness = 0.7757002422830978
coefJrIn = 0.7387551013685237
coefJrOut = 0.24039722506479938
Jcutoff = 17.79699894798633
cutoffStrength = 19.999998132669646
coefJzIn = 1.7821935085619334
coefJzOut = 1.781133216676596


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.1
# ra_coeff = 1.5
