[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 346
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 2.9
scaleRadius = 29
sersicIndex = 3
axisRatioZ = 0.9

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.048
rmaxSph = 174
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.048
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 2.9006070032553897
J0 = 3.7952899572459926
slopeIn = 1.7475816788948646
slopeOut = 1.7475819843775684
steepness = 1.5175604309033301
coefJrIn = 1.6340252259117263
coefJrOut = 0.39246289612667495
Jcutoff = 9.99336135932252
cutoffStrength = 5.842392371400622
coefJzIn = 0.9244401069480005
coefJzOut = 1.3318819093367453


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.1
# ra_coeff = 1.0
