[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 440
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 7.17
scaleRadius = 32
sersicIndex = 3
axisRatioZ = 0.8

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.053
rmaxSph = 192
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.053
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 7.171760259758516
J0 = 271.319474503618
slopeIn = 1.6316721367557256
slopeOut = 13.857985034452069
steepness = 0.7942120959966522
coefJrIn = 1.1850302447418781
coefJrOut = 0.44657568825143634
Jcutoff = 26.051438307736802
cutoffStrength = 8.570841046748347
coefJzIn = 1.0704837713077298
coefJzOut = 1.5279713443517862


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.1
# ra_coeff = 3.0
