[Potential halo]
Type = Spheroid
mass = 3162
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1156
outerCutoffRadius = 6727

[Potential bulge]
Type = Sersic
mass = 14.28
scaleRadius = 74
sersicIndex = 4
axisRatioZ = 0.3

[SelfConsistentModel halo]
rminSph = 11
rmaxSph = 6727
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.123
rmaxSph = 444
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.123
rmaxSph = 6727
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 14.282678630297447
J0 = 868.5962662636703
slopeIn = 1.6656023938252682
slopeOut = 8.511184290339074
steepness = 0.4847919307300753
coefJrIn = 0.4324011240742288
coefJrOut = 0.18639599190446332
Jcutoff = 28.476437763107196
cutoffStrength = 9.977690371394482
coefJzIn = 2.225154987877603
coefJzOut = 2.2197087054564126


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.2
# ra_coeff = 2.0
