[Potential halo]
Type = Spheroid
mass = 3162
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1149
outerCutoffRadius = 6727

[Potential bulge]
Type = Sersic
mass = 19.9
scaleRadius = 72
sersicIndex = 4
axisRatioZ = 0.9

[SelfConsistentModel halo]
rminSph = 11
rmaxSph = 6727
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.12
rmaxSph = 432
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.12
rmaxSph = 6727
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 19.903911197385916
J0 = 56.86668258783743
slopeIn = 1.9451375242753135
slopeOut = 4.15166439597875
steepness = 1.5256282148097433
coefJrIn = 1.491753546163939
coefJrOut = 0.3894975729174677
Jcutoff = 67.0519095945304
cutoffStrength = 19.9704259463568
coefJzIn = 0.8763241138035707
coefJzOut = 1.4162503385881111


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.1
# ra_coeff = 2.5
