[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 642
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 10.67
scaleRadius = 35
sersicIndex = 4
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.058
rmaxSph = 210
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.058
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 10.671969505267723
J0 = 34.58079495142747
slopeIn = 1.879986824194915
slopeOut = 5.12967576340859
steepness = 1.1612239805984899
coefJrIn = 0.9977345053399287
coefJrOut = 0.28614251536372787
Jcutoff = 25.60272367423707
cutoffStrength = 19.999999802531416
coefJzIn = 1.5948472073526263
coefJzOut = 1.9623969005551753


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.1
# ra_coeff = 2.5
