[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 325
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 7.7
scaleRadius = 51
sersicIndex = 4
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.085
rmaxSph = 306
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.085
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 7.701414802775734
J0 = 513.8804210907715
slopeIn = 1.1059252191522533
slopeOut = 4.83961732991327
steepness = 0.20000002444103196
coefJrIn = 1.0617958561628917
coefJrOut = 0.25780902836365144
Jcutoff = 22.283849245592386
cutoffStrength = 9.48774311699703
coefJzIn = 1.7172699274115846
coefJzOut = 1.75766399888513


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.2
# ra_coeff = 1.5
