[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 230
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 2.59
scaleRadius = 23
sersicIndex = 3
axisRatioZ = 0.3

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.038
rmaxSph = 138
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.038
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 2.590513859726739
J0 = 0.31985067044661825
slopeIn = 1.3136939926754643
slopeOut = 1.7481524889292916
steepness = 1.7188608814604807
coefJrIn = 0.0019159445525026174
coefJrOut = 0.26477120954152134
Jcutoff = 5.213544791440526
cutoffStrength = 3.9224674750471036
coefJzIn = 2.649579869894508
coefJzOut = 2.007614005313333


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.5
# ra_coeff = 1.0
