[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 470
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 6.98
scaleRadius = 44
sersicIndex = 3
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.073
rmaxSph = 264
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.073
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 6.981360245346709
J0 = 11.863721944326748
slopeIn = 1.7234339262369291
slopeOut = 1.7234340165741682
steepness = 1.877136737185412
coefJrIn = 2.152679724307366
coefJrOut = 0.46696530942466863
Jcutoff = 23.920776312730677
cutoffStrength = 5.112870058554355
coefJzIn = 0.42366013784631695
coefJzOut = 1.2665173452876657


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.4
# ra_coeff = 1.5
