[Potential halo]
Type = Spheroid
mass = 1585
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1089
outerCutoffRadius = 5344

[Potential bulge]
Type = Sersic
mass = 13.12
scaleRadius = 39
sersicIndex = 4
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 9
rmaxSph = 5344
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.065
rmaxSph = 234
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.065
rmaxSph = 5344
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 13.122417820487208
J0 = 26.16699129809383
slopeIn = 1.9925309329561964
slopeOut = 2.827230754154462
steepness = 1.808292085338358
coefJrIn = 2.045101174226331
coefJrOut = 0.44692098406038433
Jcutoff = 42.631838750600416
cutoffStrength = 19.999995815135478
coefJzIn = 0.4774494128868345
coefJzOut = 1.2765395079698079


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.5
# ra_coeff = 2.5
