[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 563
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 5.96
scaleRadius = 31
sersicIndex = 4
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.052
rmaxSph = 186
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.052
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 5.961243112296653
J0 = 14.983138869086822
slopeIn = 1.9462783278494897
slopeOut = 2.9918721378257693
steepness = 1.4058972525400986
coefJrIn = 1.4942793581346272
coefJrOut = 0.326034285520175
Jcutoff = 18.999263956749726
cutoffStrength = 7.443178355296217
coefJzIn = 1.2217488604142337
coefJzOut = 1.7626929326155152


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.5
# ra_coeff = 2.0
