[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 285
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 3.98
scaleRadius = 30
sersicIndex = 3
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.05
rmaxSph = 180
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.05
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.9807748651045802
J0 = 11.838428270109786
slopeIn = 1.6654881525197214
slopeOut = 3.0317861069522727
steepness = 1.0036400388155013
coefJrIn = 0.3337025469718773
coefJrOut = 0.33232513090643345
Jcutoff = 11.059325960258612
cutoffStrength = 8.730044209612403
coefJzIn = 1.3331487265140614
coefJzOut = 1.3338374345467834


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.5
# ra_coeff = 1.0
