[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 265
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 3.78
scaleRadius = 27
sersicIndex = 3
axisRatioZ = 0.9

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.045
rmaxSph = 162
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.045
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.7807962667245674
J0 = 10.821707648457684
slopeIn = 1.84789688969428
slopeOut = 1.8478970572537372
steepness = 1.2755016237166554
coefJrIn = 1.7573322920950771
coefJrOut = 0.4086575832425138
Jcutoff = 14.026772452793113
cutoffStrength = 7.874810621358667
coefJzIn = 0.894310452499052
coefJzOut = 1.2978305504764067


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.5
# ra_coeff = 1.5
