[Potential halo]
Type = Spheroid
mass = 794
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 504
outerCutoffRadius = 4245

[Potential bulge]
Type = Sersic
mass = 14.33
scaleRadius = 73
sersicIndex = 4
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 7
rmaxSph = 4245
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.122
rmaxSph = 438
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.122
rmaxSph = 4245
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 14.332670730642443
J0 = 23.490362900302674
slopeIn = 1.9457154439153719
slopeOut = 2.062093220016326
steepness = 1.1386829531732037
coefJrIn = 0.5402390992099501
coefJrOut = 0.2163859894089071
Jcutoff = 27.888907043101376
cutoffStrength = 19.999433291907447
coefJzIn = 2.16312047033398
coefJzOut = 1.8207051218503


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.0
# ra_coeff = 1.0
