[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 480
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 5.83
scaleRadius = 43
sersicIndex = 3
axisRatioZ = 0.9

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.072
rmaxSph = 258
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.072
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 5.831213090538667
J0 = 8.299715132300168
slopeIn = 1.6882348997017769
slopeOut = 1.6882352576218471
steepness = 1.4872411653338995
coefJrIn = 1.5330679598897705
coefJrOut = 0.36951739050960486
Jcutoff = 16.719574410190226
cutoffStrength = 6.131971536589495
coefJzIn = 1.0061669431139089
coefJzOut = 1.3067326488225632


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.1
# ra_coeff = 1.0
