[Potential halo]
Type = Spheroid
mass = 3162
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1080
outerCutoffRadius = 6727

[Potential bulge]
Type = Sersic
mass = 20.36
scaleRadius = 83
sersicIndex = 4
axisRatioZ = 0.3

[SelfConsistentModel halo]
rminSph = 11
rmaxSph = 6727
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.138
rmaxSph = 498
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.138
rmaxSph = 6727
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 20.363822348038077
J0 = 44964.01195640992
slopeIn = 0.7686286606011031
slopeOut = 10.71743829804214
steepness = 0.2000000142890948
coefJrIn = 0.9784567211513402
coefJrOut = 0.202572155138351
Jcutoff = 38.14493218923304
cutoffStrength = 10.903105593641769
coefJzIn = 2.0079312953769235
coefJzOut = 2.2181595889578505


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.1
# ra_coeff = 2.5
