[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 241
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 2.82
scaleRadius = 20
sersicIndex = 4
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.033
rmaxSph = 120
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.033
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 2.8205304243350193
J0 = 28.217216305861847
slopeIn = 1.762805222198284
slopeOut = 5.151067505921269
steepness = 0.7565595161891162
coefJrIn = 0.9838705601642769
coefJrOut = 0.30948052549981264
Jcutoff = 11.602413796832678
cutoffStrength = 19.587697025050964
coefJzIn = 1.0080647199178616
coefJzOut = 1.3452597372500936


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.3
# ra_coeff = 2.0
