[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 390
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 6.07
scaleRadius = 37
sersicIndex = 5
axisRatioZ = 0.7

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.062
rmaxSph = 222
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.062
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 6.071751541672747
J0 = 40342.68124735855
slopeIn = 1.4629268010930732
slopeOut = 17.61411946883313
steepness = 0.31165495684724975
coefJrIn = 0.9935019148951479
coefJrOut = 0.21939036431960943
Jcutoff = 22.853064064685586
cutoffStrength = 19.99999404653083
coefJzIn = 1.1946725157133844
coefJzOut = 1.7215432910930222


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.3
# ra_coeff = 2.5
