[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 197
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 3.01
scaleRadius = 16
sersicIndex = 3
axisRatioZ = 0.3

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.027
rmaxSph = 96
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.027
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.0106020583548876
J0 = 171.33825237411975
slopeIn = 1.6027372635165023
slopeOut = 19.99998602801845
steepness = 0.72804632592029
coefJrIn = 0.4272800163650116
coefJrOut = 0.2794913427631469
Jcutoff = 6.251221635664955
cutoffStrength = 5.990103943537001
coefJzIn = 2.155356033380861
coefJzOut = 2.242030573241604


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.2
# ra_coeff = 2.5
