[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 250
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 6.44
scaleRadius = 45
sersicIndex = 3
axisRatioZ = 0.7

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.075
rmaxSph = 270
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.075
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 6.441754260173923
J0 = 2.5797165289418196
slopeIn = 1.638377187058333
slopeOut = 2.0694237164793985
steepness = 1.9171117876689738
coefJrIn = 0.2168570558635505
coefJrOut = 0.5021307385640293
Jcutoff = 20.82649435401757
cutoffStrength = 2.851393408214174
coefJzIn = 0.8925533437311305
coefJzOut = 1.4280506062364002


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.5
# ra_coeff = 2.5
