[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 209
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 3.49
scaleRadius = 28
sersicIndex = 4
axisRatioZ = 0.7

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.047
rmaxSph = 168
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.047
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.4906383253991113
J0 = 7.509204644334441
slopeIn = 1.9740332237963862
slopeOut = 2.3738625440411307
steepness = 1.8117930165864156
coefJrIn = 1.5442919317077217
coefJrOut = 0.35201953197225366
Jcutoff = 12.745882739840319
cutoffStrength = 19.999984253051426
coefJzIn = 1.1004866097612904
coefJzOut = 1.6237254359942612


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.4
# ra_coeff = 1.5
