[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 469
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 5.55
scaleRadius = 39
sersicIndex = 3
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.065
rmaxSph = 234
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.065
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 5.551191661348144
J0 = 14.864166462987088
slopeIn = 1.7792013925570607
slopeOut = 3.7781366766130797
steepness = 1.4148732965998918
coefJrIn = 1.3835130793294506
coefJrOut = 0.3957092618672146
Jcutoff = 18.807357933369996
cutoffStrength = 19.223392640724732
coefJzIn = 1.3570418852424755
coefJzOut = 1.8959587190979545


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.4
# ra_coeff = 2.5
