[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 427
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 9.52
scaleRadius = 34
sersicIndex = 4
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.057
rmaxSph = 204
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.057
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 9.521749648683759
J0 = 17.44675147574115
slopeIn = 1.9203251466449363
slopeOut = 3.0152117091003356
steepness = 1.302049843104278
coefJrIn = 1.1238566332072792
coefJrOut = 0.31129744364846157
Jcutoff = 23.784444665697386
cutoffStrength = 19.999999780980144
coefJzIn = 0.9380716833963604
coefJzOut = 1.3443512781757692


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.2
# ra_coeff = 1.5
