[Potential halo]
Type = Spheroid
mass = 794
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 541
outerCutoffRadius = 4245

[Potential bulge]
Type = Sersic
mass = 10.87
scaleRadius = 36
sersicIndex = 3
axisRatioZ = 0.7

[SelfConsistentModel halo]
rminSph = 7
rmaxSph = 4245
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.06
rmaxSph = 216
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.06
rmaxSph = 4245
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 10.872232987060196
J0 = 19.389725523868734
slopeIn = 1.7505545739234385
slopeOut = 3.1344718523987694
steepness = 1.135572029607128
coefJrIn = 1.0327751945183996
coefJrOut = 0.4011354617778113
Jcutoff = 24.9408233334582
cutoffStrength = 15.917811408580711
coefJzIn = 1.3187610278088842
coefJzOut = 1.530368232289587


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.1
# ra_coeff = 1.5
