[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 183
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 3.88
scaleRadius = 23
sersicIndex = 4
axisRatioZ = 0.8

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.038
rmaxSph = 138
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.038
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.880740698141776
J0 = 9.383428848900936
slopeIn = 1.924485482756707
slopeOut = 3.1952139156224995
steepness = 1.4014951020935187
coefJrIn = 1.1017382737624701
coefJrOut = 0.3225669132125247
Jcutoff = 12.518557082765124
cutoffStrength = 19.999999287879568
coefJzIn = 1.1804698531408455
coefJzOut = 1.4858018392697916


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.1
# ra_coeff = 1.5
