[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 299
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 3.79
scaleRadius = 17
sersicIndex = 3
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.028
rmaxSph = 102
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.028
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.790979290624984
J0 = 588259.1642176856
slopeIn = 0.7975766153012446
slopeOut = 18.210319300575623
steepness = 0.20012514291325
coefJrIn = 0.8048434859666107
coefJrOut = 0.3788913575208102
Jcutoff = 9.32808304741656
cutoffStrength = 5.34977626528613
coefJzIn = 1.4999878502556647
coefJzOut = 1.807785886484078


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.3
# ra_coeff = 2.0
