[Potential halo]
Type = Spheroid
mass = 794
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 726
outerCutoffRadius = 4245

[Potential bulge]
Type = Sersic
mass = 14.4
scaleRadius = 56
sersicIndex = 4
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 7
rmaxSph = 4245
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.093
rmaxSph = 336
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.093
rmaxSph = 4245
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 14.402706487288489
J0 = 1714470.4411031357
slopeIn = 0.871324273500378
slopeOut = 19.117353531462214
steepness = 0.2000000138064504
coefJrIn = 1.231505963596843
coefJrOut = 0.2577972800377057
Jcutoff = 33.77842236036045
cutoffStrength = 5.303013453712437
coefJzIn = 1.5766875438774366
coefJzOut = 2.075775315025693


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.1
# ra_coeff = 3.0
