[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 265
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 3.86
scaleRadius = 30
sersicIndex = 3
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.05
rmaxSph = 180
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.05
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.860859453436573
J0 = 6.89063663342826
slopeIn = 1.849635695618491
slopeOut = 2.4131676768627868
steepness = 1.7075896870103173
coefJrIn = 1.170773943945591
coefJrOut = 0.3690605765809371
Jcutoff = 11.570476863089633
cutoffStrength = 19.214907349432092
coefJzIn = 1.5482015504799669
coefJzOut = 1.8287876628422497


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.3
# ra_coeff = 1.5
