[Potential halo]
Type = Spheroid
mass = 6310
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1731
outerCutoffRadius = 8469

[Potential bulge]
Type = Sersic
mass = 32.2
scaleRadius = 114
sersicIndex = 5
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 14
rmaxSph = 8469
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.19
rmaxSph = 684
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.19
rmaxSph = 8469
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 32.20923846653626
J0 = 82.48612465529285
slopeIn = 1.8400381281944362
slopeOut = 10.506032034501834
steepness = 4.999999911758537
coefJrIn = 0.47993253808942343
coefJrOut = 0.25961523921579693
Jcutoff = 22.340344049532185
cutoffStrength = 0.5847943049993174
coefJzIn = 1.697233148766766
coefJzOut = 1.9124144097003686


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.4
# ra_coeff = 2.5
