[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 428
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 8.25
scaleRadius = 55
sersicIndex = 3
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.092
rmaxSph = 330
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.092
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 8.251658290708578
J0 = 145497.82294947104
slopeIn = 1.5635072335636901
slopeOut = 19.999993461749757
steepness = 0.3707418377177376
coefJrIn = 0.49722346020034014
coefJrOut = 0.3322779351306868
Jcutoff = 21.973498415346345
cutoffStrength = 14.89260734851354
coefJzIn = 1.6417360888331138
coefJzOut = 1.4264732019951964


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.3
# ra_coeff = 1.0
