[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 253
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 2.66
scaleRadius = 24
sersicIndex = 3
axisRatioZ = 0.7

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.04
rmaxSph = 144
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.04
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 2.6605139125014308
J0 = 0.8769325854229028
slopeIn = 1.6039733242834153
slopeOut = 1.9853720976053464
steepness = 2.341648127863507
coefJrIn = 0.19254774626672094
coefJrOut = 0.42878218910930493
Jcutoff = 8.997187139015042
cutoffStrength = 3.751083737767681
coefJzIn = 0.9825896161095108
coefJzOut = 1.3784813494560528


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.5
# ra_coeff = 1.5
