[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 418
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 5.79
scaleRadius = 28
sersicIndex = 4
axisRatioZ = 0.9

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.047
rmaxSph = 168
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.047
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 5.7911637606111945
J0 = 842.0305453837235
slopeIn = 1.6402982367277033
slopeOut = 12.937407779598159
steepness = 0.5367380697936126
coefJrIn = 0.7611259781879518
coefJrOut = 0.2996259412927317
Jcutoff = 18.938024524331446
cutoffStrength = 19.999999559139283
coefJzIn = 1.0870180549005048
coefJzOut = 1.4554660840718812


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.4
# ra_coeff = 2.0
