[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 422
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 4.38
scaleRadius = 38
sersicIndex = 3
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.063
rmaxSph = 228
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.063
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 4.380864362059459
J0 = 13.326699662719664
slopeIn = 1.7526890318872026
slopeOut = 3.055102352428752
steepness = 1.0452418033936794
coefJrIn = 1.0453520719459921
coefJrOut = 0.37735710737010586
Jcutoff = 15.329262734770944
cutoffStrength = 16.69152934454997
coefJzIn = 1.4623262996444457
coefJzOut = 1.6554005279512694


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.0
# ra_coeff = 1.5
