[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 446
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 7.44
scaleRadius = 50
sersicIndex = 4
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.083
rmaxSph = 300
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.083
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 7.441374081365542
J0 = 108.2516753881836
slopeIn = 1.8121881140504155
slopeOut = 7.9028797240107975
steepness = 0.9248860547278955
coefJrIn = 1.1719944387548213
coefJrOut = 0.3690136449492404
Jcutoff = 37.957229981257136
cutoffStrength = 19.999996244162194
coefJzIn = 0.9140027806225893
coefJzOut = 1.3154931775253798


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.2
# ra_coeff = 3.0
