[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 224
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 3.19
scaleRadius = 23
sersicIndex = 4
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.038
rmaxSph = 138
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.038
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.1905917260064904
J0 = 27.346325974245907
slopeIn = 1.8278543149378865
slopeOut = 5.570376025229591
steepness = 0.9500769406450156
coefJrIn = 1.1773097745817205
coefJrOut = 0.35138206388468196
Jcutoff = 15.282040995151615
cutoffStrength = 19.999992041186342
coefJzIn = 0.9113451127091398
coefJzOut = 1.324308968057659


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.2
# ra_coeff = 2.5
