[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 270
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 3.98
scaleRadius = 29
sersicIndex = 4
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.048
rmaxSph = 174
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.048
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.9807220621776134
J0 = 12.158468545957428
slopeIn = 1.927898926519802
slopeOut = 3.5331298152842368
steepness = 1.3723750192623823
coefJrIn = 0.8078286177015124
coefJrOut = 0.2635027683338728
Jcutoff = 12.08030117973023
cutoffStrength = 19.950357902911538
coefJzIn = 1.7429264342793407
coefJzOut = 1.8321787243030487


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.0
# ra_coeff = 1.5
