[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 334
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 3.4
scaleRadius = 26
sersicIndex = 3
axisRatioZ = 0.8

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.043
rmaxSph = 156
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.043
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.4008696798432445
J0 = 8.711138332970263
slopeIn = 1.75581667897083
slopeOut = 3.0855392972417053
steepness = 1.2237852941014018
coefJrIn = 1.1494254076913202
coefJrOut = 0.4185540193697047
Jcutoff = 12.409374696682695
cutoffStrength = 17.25624423008929
coefJzIn = 1.1447634314210393
coefJzOut = 1.4319510950978442


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.1
# ra_coeff = 1.5
