[Potential halo]
Type = Spheroid
mass = 6310
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1179
outerCutoffRadius = 8469

[Potential bulge]
Type = Sersic
mass = 25.54
scaleRadius = 66
sersicIndex = 5
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 14
rmaxSph = 8469
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.11
rmaxSph = 396
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.11
rmaxSph = 8469
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 25.54714280363344
J0 = 71.70280434843335
slopeIn = 1.9974526786360371
slopeOut = 5.885187860346912
steepness = 1.2597912328806091
coefJrIn = 0.8678929459725864
coefJrOut = 0.19224784375936296
Jcutoff = 49.82141705753422
cutoffStrength = 13.707334835161202
coefJzIn = 1.8166865599511177
coefJzOut = 2.2083597424938097


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.2
# ra_coeff = 3.0
