[Potential halo]
Type = Spheroid
mass = 794
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 705
outerCutoffRadius = 4245

[Potential bulge]
Type = Sersic
mass = 14.68
scaleRadius = 47
sersicIndex = 3
axisRatioZ = 0.7

[SelfConsistentModel halo]
rminSph = 7
rmaxSph = 4245
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.078
rmaxSph = 282
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.078
rmaxSph = 4245
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 14.683684239411043
J0 = 29.119386113587762
slopeIn = 1.8033636415781662
slopeOut = 3.7927372804195856
steepness = 1.6094604864447413
coefJrIn = 1.5866612485414775
coefJrOut = 0.4909100773950563
Jcutoff = 41.22804907316946
cutoffStrength = 19.999893378076013
coefJzIn = 1.0142236230301707
coefJzOut = 1.6145321486072512


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.3
# ra_coeff = 2.5
