[Potential halo]
Type = Spheroid
mass = 1585
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 631
outerCutoffRadius = 5344

[Potential bulge]
Type = Sersic
mass = 16.22
scaleRadius = 63
sersicIndex = 4
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 9
rmaxSph = 5344
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.105
rmaxSph = 378
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.105
rmaxSph = 5344
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 16.222964147889485
J0 = 63.84236241711144
slopeIn = 1.874009248091487
slopeOut = 5.5180953492353675
steepness = 1.1379746600713396
coefJrIn = 1.1254230781778425
coefJrOut = 0.2919756356243047
Jcutoff = 44.98356662136942
cutoffStrength = 12.556362366005722
coefJzIn = 1.5060311389147671
coefJzOut = 2.004510244713807


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.2
# ra_coeff = 3.0
