[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 214
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 3.46
scaleRadius = 27
sersicIndex = 3
axisRatioZ = 0.8

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.045
rmaxSph = 162
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.045
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.4609225577660974
J0 = 11328.324086255614
slopeIn = 1.2828962892363158
slopeOut = 19.999994781251274
steepness = 0.37193924604842243
coefJrIn = 1.1984637946053394
coefJrOut = 0.45672708779555354
Jcutoff = 15.597190100656848
cutoffStrength = 5.251741973775169
coefJzIn = 0.9861774083674893
coefJzOut = 1.5281889226709697


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.2
# ra_coeff = 3.0
