[Potential halo]
Type = Spheroid
mass = 3162
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 862
outerCutoffRadius = 6727

[Potential bulge]
Type = Sersic
mass = 15.63
scaleRadius = 60
sersicIndex = 5
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 11
rmaxSph = 6727
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.1
rmaxSph = 360
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.1
rmaxSph = 6727
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 15.634506023070392
J0 = 85.0944102912044
slopeIn = 2.0029533777402984
slopeOut = 5.850806996777619
steepness = 1.1112160600732828
coefJrIn = 0.6376046821854041
coefJrOut = 0.19603139378722503
Jcutoff = 36.718645185453674
cutoffStrength = 11.56836921125593
coefJzIn = 1.7674940310354905
coefJzOut = 1.8896657751232206


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.2
# ra_coeff = 2.0
