[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 198
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 3.93
scaleRadius = 24
sersicIndex = 3
axisRatioZ = 0.3

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.04
rmaxSph = 144
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.04
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.9307722737784543
J0 = 70851.26163464157
slopeIn = 0.7867545580959385
slopeOut = 12.880737558417033
steepness = 0.200000002088704
coefJrIn = 0.3279566573193817
coefJrOut = 0.273616965847836
Jcutoff = 8.08171966173229
cutoffStrength = 7.959930859442416
coefJzIn = 2.433400331987749
coefJzOut = 2.071342529866981


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.3
# ra_coeff = 1.5
