[Potential halo]
Type = Spheroid
mass = 794
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 838
outerCutoffRadius = 4245

[Potential bulge]
Type = Sersic
mass = 11.01
scaleRadius = 50
sersicIndex = 3
axisRatioZ = 0.3

[SelfConsistentModel halo]
rminSph = 7
rmaxSph = 4245
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.083
rmaxSph = 300
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.083
rmaxSph = 4245
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 11.0121208651372
J0 = 9.393325450434666
slopeIn = 1.890744338141294
slopeOut = 1.9160273730050974
steepness = 1.623030927852616
coefJrIn = 0.8850258987715109
coefJrOut = 0.2542490504032413
Jcutoff = 17.285699914860544
cutoffStrength = 19.999998604205768
coefJzIn = 1.9990278619549458
coefJzOut = 2.216954629519756


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.5
# ra_coeff = 1.5
