[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 388
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 8.69
scaleRadius = 51
sersicIndex = 4
axisRatioZ = 0.3

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.085
rmaxSph = 306
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.085
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 8.691677113580013
J0 = 80.97510330533281
slopeIn = 1.7053870059402125
slopeOut = 5.586331370989555
steepness = 0.6152623638758953
coefJrIn = 0.6651488536118668
coefJrOut = 0.18205875180496642
Jcutoff = 19.227609320974185
cutoffStrength = 19.999996036569275
coefJzIn = 2.1384933531608006
coefJzOut = 2.279890470043393


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.1
# ra_coeff = 2.5
