[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 253
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 7.15
scaleRadius = 39
sersicIndex = 3
axisRatioZ = 0.3

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.065
rmaxSph = 234
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.065
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 7.151389574493609
J0 = 0.969314422590097
slopeIn = 1.4809129542929085
slopeOut = 1.874467242705384
steepness = 1.8245544301936532
coefJrIn = 0.011717135589769518
coefJrOut = 0.28903767660673846
Jcutoff = 12.173629374232284
cutoffStrength = 3.4593394007905403
coefJzIn = 2.300579035798304
coefJzOut = 2.0673624546047624


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.5
# ra_coeff = 1.5
