[Potential halo]
Type = Spheroid
mass = 6310
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 2005
outerCutoffRadius = 8469

[Potential bulge]
Type = Sersic
mass = 33.07
scaleRadius = 103
sersicIndex = 4
axisRatioZ = 0.7

[SelfConsistentModel halo]
rminSph = 14
rmaxSph = 8469
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.172
rmaxSph = 618
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.172
rmaxSph = 8469
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 33.07689719080372
J0 = 65.89501573341259
slopeIn = 1.9238332134273854
slopeOut = 3.609240727166263
steepness = 1.4114536725053204
coefJrIn = 1.2779646128335371
coefJrOut = 0.358052141878064
Jcutoff = 86.28450506882791
cutoffStrength = 17.322528974401592
coefJzIn = 1.1997303909800068
coefJzOut = 1.66061541037063


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.1
# ra_coeff = 2.0
