[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 337
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 10.95
scaleRadius = 39
sersicIndex = 3
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.065
rmaxSph = 234
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.065
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 10.952351115632704
J0 = 2719.432131816403
slopeIn = 1.2438276408571838
slopeOut = 7.712887975132214
steepness = 0.3041597707699316
coefJrIn = 0.9943529745990776
coefJrOut = 0.34045948547450755
Jcutoff = 24.0933444628169
cutoffStrength = 9.001920669185273
coefJzIn = 1.5896510206438568
coefJzOut = 1.82605343636702


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.1
# ra_coeff = 2.0
