[Potential halo]
Type = Spheroid
mass = 6310
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1362
outerCutoffRadius = 8469

[Potential bulge]
Type = Sersic
mass = 21.45
scaleRadius = 50
sersicIndex = 3
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 14
rmaxSph = 8469
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.083
rmaxSph = 300
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.083
rmaxSph = 8469
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 21.454174011578566
J0 = 295.8346315222662
slopeIn = 1.6695074511633674
slopeOut = 10.748503005756586
steepness = 0.9061885758425966
coefJrIn = 1.1231206766575497
coefJrOut = 0.4472064503498245
Jcutoff = 56.66321819810158
cutoffStrength = 19.99999651357401
coefJzIn = 0.9384396616712252
coefJzOut = 1.2763967748250877


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.2
# ra_coeff = 2.5
