[Potential halo]
Type = Spheroid
mass = 794
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 802
outerCutoffRadius = 4245

[Potential bulge]
Type = Sersic
mass = 11.2
scaleRadius = 36
sersicIndex = 3
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 7
rmaxSph = 4245
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.06
rmaxSph = 216
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.06
rmaxSph = 4245
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 11.202211681650747
J0 = 14.70978879322319
slopeIn = 1.8031020418211636
slopeOut = 2.7680459251541385
steepness = 1.612735587857767
coefJrIn = 1.7017630693931174
coefJrOut = 0.44357308761629394
Jcutoff = 26.64138409409232
cutoffStrength = 16.854397819512855
coefJzIn = 1.057440408171147
coefJzOut = 1.740354101702101


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.5
# ra_coeff = 2.0
