[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 369
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 4.42
scaleRadius = 19
sersicIndex = 4
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.032
rmaxSph = 114
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.032
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 4.420813983563559
J0 = 24.81273456443994
slopeIn = 1.8444944112301913
slopeOut = 6.7178313014692534
steepness = 0.9957662740597367
coefJrIn = 0.8444955504620204
coefJrOut = 0.24284828764872313
Jcutoff = 10.88421651008438
cutoffStrength = 13.749402249235999
coefJzIn = 1.8138136410597778
coefJzOut = 2.1609299580052657


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.1
# ra_coeff = 3.0
