[Potential halo]
Type = Spheroid
mass = 6310
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1500
outerCutoffRadius = 8469

[Potential bulge]
Type = Sersic
mass = 19.48
scaleRadius = 51
sersicIndex = 5
axisRatioZ = 0.8

[SelfConsistentModel halo]
rminSph = 14
rmaxSph = 8469
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.085
rmaxSph = 306
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.085
rmaxSph = 8469
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 19.4858725189251
J0 = 349.7683932678727
slopeIn = 1.8584108215560922
slopeOut = 10.22628261504645
steepness = 0.772234058541466
coefJrIn = 0.7237465931811492
coefJrOut = 0.2818923655202018
Jcutoff = 58.10873246635227
cutoffStrength = 7.694314834249952
coefJzIn = 1.1730327093343733
coefJzOut = 1.626748066059477


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.4
# ra_coeff = 3.0
