[Potential halo]
Type = Spheroid
mass = 1585
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 725
outerCutoffRadius = 5344

[Potential bulge]
Type = Sersic
mass = 19.05
scaleRadius = 45
sersicIndex = 4
axisRatioZ = 0.3

[SelfConsistentModel halo]
rminSph = 9
rmaxSph = 5344
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.075
rmaxSph = 270
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.075
rmaxSph = 5344
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 19.053468243402392
J0 = 99.31121538711594
slopeIn = 1.8284744397782802
slopeOut = 5.142780881118358
steepness = 0.734542981565965
coefJrIn = 0.5083199724698549
coefJrOut = 0.1800025645671094
Jcutoff = 25.837983106461923
cutoffStrength = 13.510511231469508
coefJzIn = 2.247786798855398
coefJzOut = 2.221871271265129


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.0
# ra_coeff = 2.0
