[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 441
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 3.81
scaleRadius = 28
sersicIndex = 4
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.047
rmaxSph = 168
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.047
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.8107092515390986
J0 = 8.95480119405374
slopeIn = 1.952549609214556
slopeOut = 1.9525506981972467
steepness = 1.5977363501239112
coefJrIn = 1.9565580535487705
coefJrOut = 0.40624390657779874
Jcutoff = 15.90132538048781
cutoffStrength = 4.195408861167964
coefJzIn = 0.5217209732256147
coefJzOut = 1.2968780467111007


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.3
# ra_coeff = 2.0
