[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 398
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 5.85
scaleRadius = 34
sersicIndex = 4
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.057
rmaxSph = 204
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.057
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 5.8510790033049265
J0 = 35.10361450950866
slopeIn = 1.8772871770615707
slopeOut = 6.027457665758564
steepness = 1.0888558318717139
coefJrIn = 0.8973940154475432
coefJrOut = 0.2743990503597509
Jcutoff = 18.68903730219906
cutoffStrength = 14.147190878383913
coefJzIn = 1.6264237070613778
coefJzOut = 1.967335191770025


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.0
# ra_coeff = 2.5
