[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 385
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 6.64
scaleRadius = 45
sersicIndex = 3
axisRatioZ = 0.9

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.075
rmaxSph = 270
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.075
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 6.64137812050255
J0 = 19.69887881074093
slopeIn = 1.8366686967690156
slopeOut = 3.3463090173067016
steepness = 1.7036965912836768
coefJrIn = 1.9311150717791592
coefJrOut = 0.549921662796757
Jcutoff = 30.917779193948824
cutoffStrength = 19.999999601307973
coefJzIn = 0.6311265570303589
coefJzOut = 1.3558917960819783


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.4
# ra_coeff = 2.5
