[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 185
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 2.99
scaleRadius = 24
sersicIndex = 3
axisRatioZ = 0.7

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.04
rmaxSph = 144
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.04
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 2.990577668564635
J0 = 7.006552676937266
slopeIn = 1.8265006241466055
slopeOut = 2.8982911864113223
steepness = 1.760284700658609
coefJrIn = 1.7006573482745817
coefJrOut = 0.4810772184796843
Jcutoff = 12.21132192334258
cutoffStrength = 19.999945989341608
coefJzIn = 0.9587282388658475
coefJzOut = 1.6036423144823841


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.4
# ra_coeff = 2.0
