[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 302
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 3.68
scaleRadius = 17
sersicIndex = 3
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.028
rmaxSph = 102
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.028
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.6807073295588473
J0 = 8.709979317497972
slopeIn = 1.7848578995218758
slopeOut = 3.8388868845908997
steepness = 1.4413487663861413
coefJrIn = 1.4568514048336363
coefJrOut = 0.4459745866037377
Jcutoff = 11.33691050307149
cutoffStrength = 17.312574836319115
coefJzIn = 1.1920438166708616
coefJzOut = 1.7501413993721928


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.3
# ra_coeff = 2.5
