[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 423
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 5.23
scaleRadius = 36
sersicIndex = 3
axisRatioZ = 0.7

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.06
rmaxSph = 216
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.06
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 5.231074381079045
J0 = 2.3695034127986214
slopeIn = 1.7192074352358784
slopeOut = 2.092289130211305
steepness = 2.8186461377718706
coefJrIn = 0.42319414796216476
coefJrOut = 0.5700522795792904
Jcutoff = 17.366920572665055
cutoffStrength = 2.420976363006584
coefJzIn = 1.0992985339403052
coefJzOut = 1.4477552229731752


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.4
# ra_coeff = 3.0
