[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 301
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 3.98
scaleRadius = 23
sersicIndex = 3
axisRatioZ = 0.8

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.038
rmaxSph = 138
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.038
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.9811311981715525
J0 = 124.44658411356254
slopeIn = 1.5871229473775958
slopeOut = 6.362052432245948
steepness = 0.5885879585262278
coefJrIn = 0.7737968335046813
coefJrOut = 0.37686525484706096
Jcutoff = 12.36772717958781
cutoffStrength = 11.12075273001161
coefJzIn = 1.2211757578618
coefJzOut = 1.42096928976399


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.3
# ra_coeff = 1.5
