[Potential halo]
Type = Spheroid
mass = 794
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 543
outerCutoffRadius = 4245

[Potential bulge]
Type = Sersic
mass = 8.03
scaleRadius = 46
sersicIndex = 4
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 7
rmaxSph = 4245
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.077
rmaxSph = 276
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.077
rmaxSph = 4245
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 8.031501368073885
J0 = 18.169222580078692
slopeIn = 1.9373394434978115
slopeOut = 3.2073067644371043
steepness = 1.5322392330959755
coefJrIn = 0.9618498372774437
coefJrOut = 0.3003895592969912
Jcutoff = 23.503373376698892
cutoffStrength = 13.688841099748934
coefJzIn = 1.5239373500568307
coefJzOut = 1.6989845194619413


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.0
# ra_coeff = 1.5
