[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 319
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 4.55
scaleRadius = 27
sersicIndex = 4
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.045
rmaxSph = 162
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.045
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 4.551615799257502
J0 = 6.706968703812595
slopeIn = 1.9817234233429801
slopeOut = 2.347035811202568
steepness = 1.8418790538283185
coefJrIn = 1.0098286304445336
coefJrOut = 0.2581556640820983
Jcutoff = 10.673944511356941
cutoffStrength = 19.999492588313842
coefJzIn = 1.7993906783589981
coefJzOut = 2.0569540229524774


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.5
# ra_coeff = 1.5
