[Potential halo]
Type = Spheroid
mass = 6310
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1664
outerCutoffRadius = 8469

[Potential bulge]
Type = Sersic
mass = 17.94
scaleRadius = 70
sersicIndex = 5
axisRatioZ = 0.7

[SelfConsistentModel halo]
rminSph = 14
rmaxSph = 8469
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.117
rmaxSph = 420
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.117
rmaxSph = 8469
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 17.945507585841625
J0 = 58.59828738084819
slopeIn = 2.009629293568808
slopeOut = 4.631003935144178
steepness = 1.4044640187130482
coefJrIn = 1.3379176016890177
coefJrOut = 0.3137535496665483
Jcutoff = 62.11664617669207
cutoffStrength = 16.741226582326473
coefJzIn = 1.179414220493974
coefJzOut = 1.7296826221301131


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.2
# ra_coeff = 3.0
