[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 208
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 2.55
scaleRadius = 29
sersicIndex = 3
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.048
rmaxSph = 174
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.048
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 2.5504873758451105
J0 = 7.339408532190244
slopeIn = 1.8024012514175123
slopeOut = 3.6599466840238155
steepness = 1.499805422603792
coefJrIn = 1.2241961396339027
coefJrOut = 0.3396117130828222
Jcutoff = 9.403401741470507
cutoffStrength = 19.996770633706923
coefJzIn = 1.5848100970824723
coefJzOut = 2.0703008425774265


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.5
# ra_coeff = 2.5
