[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 281
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 3.99
scaleRadius = 35
sersicIndex = 3
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.058
rmaxSph = 210
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.058
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.9907717377209035
J0 = 12.849573998347504
slopeIn = 1.78769665921068
slopeOut = 4.002319475961519
steepness = 1.2904198274959833
coefJrIn = 1.119086692412691
coefJrOut = 0.3238155153579532
Jcutoff = 12.825221087356589
cutoffStrength = 19.999999917120572
coefJzIn = 1.6624599406818108
coefJzOut = 2.0737446740580014


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.4
# ra_coeff = 2.5
