[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 236
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 3.36
scaleRadius = 21
sersicIndex = 4
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.035
rmaxSph = 126
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.035
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.3606201735518146
J0 = 109.17944783472797
slopeIn = 1.5935895389238925
slopeOut = 5.001804986496753
steepness = 0.39666438652670405
coefJrIn = 0.7497323767291175
coefJrOut = 0.23792757967651065
Jcutoff = 9.343850458142137
cutoffStrength = 17.810050135163927
coefJzIn = 1.7561805058655597
coefJzOut = 1.7858641193872384


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.2
# ra_coeff = 1.5
