[Potential halo]
Type = Spheroid
mass = 1585
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 894
outerCutoffRadius = 5344

[Potential bulge]
Type = Sersic
mass = 11.1
scaleRadius = 34
sersicIndex = 4
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 9
rmaxSph = 5344
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.057
rmaxSph = 204
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.057
rmaxSph = 5344
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 11.10217572273403
J0 = 24.24179213544924
slopeIn = 1.9255931494662812
slopeOut = 4.0897081609970485
steepness = 1.4623579456511044
coefJrIn = 1.3521549297792708
coefJrOut = 0.3441906409106184
Jcutoff = 28.939918056734175
cutoffStrength = 19.99999903893107
coefJzIn = 1.2718375007470766
coefJzOut = 1.8285266716904605


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.3
# ra_coeff = 2.5
