[Potential halo]
Type = Spheroid
mass = 1585
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1064
outerCutoffRadius = 5344

[Potential bulge]
Type = Sersic
mass = 15.05
scaleRadius = 73
sersicIndex = 4
axisRatioZ = 0.9

[SelfConsistentModel halo]
rminSph = 9
rmaxSph = 5344
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.122
rmaxSph = 438
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.122
rmaxSph = 5344
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 15.052960804343304
J0 = 67.57648164858466
slopeIn = 1.863102523172853
slopeOut = 4.5166040370210485
steepness = 1.0543843466110834
coefJrIn = 1.0734268615068734
coefJrOut = 0.32979968692102063
Jcutoff = 51.481178535074186
cutoffStrength = 19.59850217846741
coefJzIn = 1.0497352685741397
coefJzOut = 1.4246973724916523


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.2
# ra_coeff = 2.0
