[Potential halo]
Type = Spheroid
mass = 398
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 400
outerCutoffRadius = 3372

[Potential bulge]
Type = Sersic
mass = 6.23
scaleRadius = 39
sersicIndex = 4
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 6
rmaxSph = 3372
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.065
rmaxSph = 234
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.065
rmaxSph = 3372
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 6.2311598441924865
J0 = 89.38117541848126
slopeIn = 1.80209608134239
slopeOut = 8.75112658416297
steepness = 0.8733669902489379
coefJrIn = 0.9380920132760984
coefJrOut = 0.26930586389577266
Jcutoff = 21.536817555067586
cutoffStrength = 19.99999576054078
coefJzIn = 1.5899106441934319
coefJzOut = 1.9958975269800379


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.0
# ra_coeff = 3.0
