[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 297
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 7.12
scaleRadius = 47
sersicIndex = 4
axisRatioZ = 0.5

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.078
rmaxSph = 282
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.078
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 7.121310750734938
J0 = 37.65959604795834
slopeIn = 1.7986692017053116
slopeOut = 7.717624904096735
steepness = 1.1611898487325927
coefJrIn = 0.46421100560078815
coefJrOut = 0.3964245508858386
Jcutoff = 31.095104684364998
cutoffStrength = 19.999991658218796
coefJzIn = 1.6010208785132176
coefJzOut = 1.942975375374599


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.4
# ra_coeff = 3.0
