[Potential halo]
Type = Spheroid
mass = 6310
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1120
outerCutoffRadius = 8469

[Potential bulge]
Type = Sersic
mass = 21.14
scaleRadius = 74
sersicIndex = 4
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 14
rmaxSph = 8469
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.123
rmaxSph = 444
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.123
rmaxSph = 8469
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 21.14395929503373
J0 = 216.56215516774245
slopeIn = 1.8192422256899266
slopeOut = 7.90285093933889
steepness = 0.9411678098904049
coefJrIn = 1.1695887336637856
coefJrOut = 0.36495951998035875
Jcutoff = 77.72849834172837
cutoffStrength = 19.999997169631005
coefJzIn = 0.9152056331681072
coefJzOut = 1.3175202400098207


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.2
# ra_coeff = 3.0
