[Potential halo]
Type = Spheroid
mass = 100
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 230
outerCutoffRadius = 2127

[Potential bulge]
Type = Sersic
mass = 2.2
scaleRadius = 15
sersicIndex = 3
axisRatioZ = 0.4

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2127
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.025
rmaxSph = 90
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.025
rmaxSph = 2127
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 2.2004298965283726
J0 = 429.0835121221335
slopeIn = 1.6077682859586344
slopeOut = 8.929364590258109
steepness = 0.47450293783692116
coefJrIn = 0.5057713875360607
coefJrOut = 0.2984995859555757
Jcutoff = 5.6104400942350825
cutoffStrength = 19.99999822839746
coefJzIn = 2.032009624327065
coefJzOut = 1.8047889022011792


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.2
# ra_coeff = 1.5
