[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 280
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 3.62
scaleRadius = 33
sersicIndex = 3
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.055
rmaxSph = 198
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.055
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.620717234338515
J0 = 227.08941003335278
slopeIn = 1.6741792761881922
slopeOut = 11.703842699149599
steepness = 0.7807025730976924
coefJrIn = 0.4069624324515217
coefJrOut = 0.3580477208112804
Jcutoff = 11.607687192437815
cutoffStrength = 10.538992952556796
coefJzIn = 1.5786802543387952
coefJzOut = 1.3998400074521866


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.4
# ra_coeff = 1.0
