[Potential halo]
Type = Spheroid
mass = 3162
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 1520
outerCutoffRadius = 6727

[Potential bulge]
Type = Sersic
mass = 13.78
scaleRadius = 54
sersicIndex = 4
axisRatioZ = 1.0

[SelfConsistentModel halo]
rminSph = 11
rmaxSph = 6727
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.09
rmaxSph = 324
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.09
rmaxSph = 6727
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 13.782552984717592
J0 = 66.75532574501875
slopeIn = 1.8976114983327468
slopeOut = 5.351852163217082
steepness = 1.2203554986362393
coefJrIn = 1.493578882528038
coefJrOut = 0.3947367131984245
Jcutoff = 55.72253863523555
cutoffStrength = 19.999990391761724
coefJzIn = 0.753210558735981
coefJzOut = 1.3026316434007876


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = 0.0
# ra_coeff = 3.0
