[Potential halo]
Type = Spheroid
mass = 200
axisRatioZ = 1.0
alpha = 1.0
gamma = 1
beta = 3
scaleRadius = 412
outerCutoffRadius = 2678

[Potential bulge]
Type = Sersic
mass = 3.78
scaleRadius = 18
sersicIndex = 3
axisRatioZ = 0.6

[SelfConsistentModel halo]
rminSph = 4
rmaxSph = 2678
sizeRadialSph = 35
lmaxAngularSph = 6

[SelfConsistentModel bulge]
rminSph = 0.03
rmaxSph = 108
sizeRadialSph = 30
lmaxAngularSph = 6

[SelfConsistentModel]
rminSph = 0.03
rmaxSph = 2678
sizeRadialSph = 40
lmaxAngularSph = 6
useActionInterpolation = false

[DF bulge]
type = DoublePowerLaw
mass = 3.7807289466820535
J0 = 23.64101539480393
slopeIn = 1.7418925105075966
slopeOut = 7.005483446226477
steepness = 1.1583400200299667
coefJrIn = 1.2063571353170923
coefJrOut = 0.4107600456256086
Jcutoff = 12.223262008358956
cutoffStrength = 19.999988907271234
coefJzIn = 1.310844466271877
coefJzOut = 1.7720869138167803


# --- Anisotropy parameters (randomly drawn) ---
# beta0    = -0.1
# ra_coeff = 3.0
